### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by mfcltd** [thomascys/solaxcloud#1]
Hi! 
Thanks for creating this. I am trying really hard to get info on my inverter into HA and EmonCMS but it is proving difficult.! 'm trying your component on my Hass.io instance and I am getting the following errors. Any ideas? Thanks.

2020-01-03 20:01:45 ERROR (MainThread) [homeassistant.components.sensor] solaxcloud: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/solaxcloud/sensor.py", line 157, in update
    self.solax_cloud.get_data()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/solaxcloud/sensor.py", line 50, in get_data
    self.data = json_obj['result'].pop()
IndexError: pop from empty list

**Comment by thomascys** [comment]
My first guess is that the information you provided to connect to the api is probably wrong.
Verify the following:
Login into solaxcloud.com then go to "inverters":
The "Inverter SN" is "your-inverter-serial"
The "Registration No." is "your-inverter-ssid"

Let me know if this works out for you.

**Comment by mfcltd** [comment]
Okay I did get the serial number wrong but still get this error (username redacted!):

2020-01-04 09:31:44 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for solaxcloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-01-04 09:31:45 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform solaxcloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/ entity_platform.py<http://entity_platform.py>", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/ tasks.py<http://tasks.py>", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/ thread.py<http://thread.py>", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/solaxcloud/ sensor.py<http://sensor.py>", line 15, in setup_platform
    solax_cloud = SolaxCloud(hass, 'your-username', 'your-password', 'your-inverter-serial', 'your-inverter-ssid')
  File "/config/custom_components/solaxcloud/ sensor.py<http://sensor.py>", line 21, in __init__
    self._username = xxxxx
NameError: name 'xxxxx' is not defined

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by thomascys** [comment]
You only needed you replace the following with your credentials: 
solax_cloud = SolaxCloud(hass, 'your-username', 'your-password', 'your-inverter-serial', 'your-inverter-ssid')

I'll try to rewrite the component so it's much easier to configure.

**Comment by mfcltd** [comment]
Ah I see. I have corrected this, but unfortunately still receiving errors:

2020-01-04 16:38:26 ERROR (MainThread) [homeassistant.components.sensor] solaxcloud: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
   await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/solaxcloud/sensor.py", line 130, in update
    self.solax_cloud.get_data()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/solaxcloud/sensor.py", line 50, in get_data
    self.data = json_obj['result'].pop()
IndexError: pop from empty list

**Comment by thomascys** [comment]
I rewrote the component so that credentials are now configurable. See the README.md on how to setup this correctly:
https://github.com/thomascys/solaxcloud/blob/master/README.md

I've noticed that the API responses are really slow sometimes (+30seconds). I guess a future version of this component will need to get those responses in an async way.
